<script src="https://giscus.app/client.js"
        data-repo="FunTim41/funtim41.github.io"
        data-repo-id="R_kgDONjG8ww"
        data-category="Q&A"
        data-category-id="DIC_kwDONjG8w84Cllg4"
        data-mapping="title"
        data-strict="0"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="top"
        data-theme="preferred_color_scheme"
        data-lang="zh-CN"
        data-loading="lazy"
        crossorigin="anonymous"
        async>
</script>